env=Environment(CPPPATH=['/usr/local/include/boost_1_79_0/', 'include/'],
    CPPDEFINES=[],
    LIBS=[],
    SCONS_CXX_STANDARD="c++20"
    )


env.Program('main', Glob('src/*.cpp'))   
# Program('main.cpp')